apiVersion: apps/v1
kind: Deployment
metadata:
  name: kootone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kootone
  template:
    metadata:
      labels:
        app: kootone
    spec:
      containers:
      - image: okteto.dev/kootone:latest
        name: kootone
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "9f0cfd2f-f755-4a0c-a14d-146c5a74be43"
        - name: Vless_Path
          value: "/fgh76u4wrgjyu"
        - name: Vmess_UUID
          value: "9f0cfd2f-f755-4a0c-a14d-146c5a74be43"
        - name: Vmess_Path
          value: "/fdbjui75u56ehtd"
        - name: Share_Path
          value: "/v2link"
